// Code generated by go-swagger; DO NOT EDIT.

package athletes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetStatsParams creates a new GetStatsParams object
// with the default values initialized.
func NewGetStatsParams() *GetStatsParams {
	var ()
	return &GetStatsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatsParamsWithTimeout creates a new GetStatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStatsParamsWithTimeout(timeout time.Duration) *GetStatsParams {
	var ()
	return &GetStatsParams{

		timeout: timeout,
	}
}

// NewGetStatsParamsWithContext creates a new GetStatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStatsParamsWithContext(ctx context.Context) *GetStatsParams {
	var ()
	return &GetStatsParams{

		Context: ctx,
	}
}

// NewGetStatsParamsWithHTTPClient creates a new GetStatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStatsParamsWithHTTPClient(client *http.Client) *GetStatsParams {
	var ()
	return &GetStatsParams{
		HTTPClient: client,
	}
}

/*GetStatsParams contains all the parameters to send to the API endpoint
for the get stats operation typically these are written to a http.Request
*/
type GetStatsParams struct {

	/*ID
	  The identifier of the athlete. Must match the authenticated athlete.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stats params
func (o *GetStatsParams) WithTimeout(timeout time.Duration) *GetStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stats params
func (o *GetStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stats params
func (o *GetStatsParams) WithContext(ctx context.Context) *GetStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stats params
func (o *GetStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stats params
func (o *GetStatsParams) WithHTTPClient(client *http.Client) *GetStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stats params
func (o *GetStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get stats params
func (o *GetStatsParams) WithID(id int64) *GetStatsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stats params
func (o *GetStatsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
