name: Push to Mirror
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - run: |
        git remote add mirror ${{ secrets.GIT_MIRROR_URL }}
        git config --global user.email ${{ secrets.GIT_MIRROR_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_MIRROR_USER_NAME }}
        git checkout master
        git push -u mirror master
        git push --tags mirror